async def awaitable_exception() -> Exception:
    return Exception()
